apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-debian-docker
spec:
  selector:
    matchLabels:
      app: my-debian-docker
  template:
    metadata:
      labels:
        app: my-debian-docker
    spec:
      containers:
      - name: c-my-debian-docker
        securityContext:
          privileged: true
        image: debian_docker_xc
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
       # ports:
        # - containerPort: <Port>
