- hosts: c_debian_python_xc
  tasks:

  - name: changer bind-address = 127.0.0.1 > *
    replace:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: 'bind\-address\s\+=\s\+172\.0\.0\.1\s*$'
      replace: 'bind\-address\s=\s\*'

##################
# - hosts: 172.17.0.2 # group : c_debian_python_xc
#   tasks:

#   - name: changer bind-address = 127.0.0.1 > *
#     fetch:
#       src: /etc/mysql/mariadb.conf.d/50-server.cnf
#       dest: /home/formation/tmp/exercies/02_14/playbooks/